# Generated by Django 5.0.1 on 2024-02-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpAccountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp_name', models.CharField(max_length=120)),
                ('emp_mobile', models.CharField(max_length=100)),
                ('emp_mail', models.CharField(max_length=150)),
                ('emp_address', models.TextField()),
                ('emp_states', models.CharField(max_length=100)),
                ('emp_college_name', models.CharField(max_length=150)),
                ('emp_marks', models.CharField(max_length=80)),
                ('emp_education', models.CharField(max_length=100)),
                ('emp_field', models.CharField(max_length=100)),
                ('emp_category', models.CharField(max_length=60)),
                ('emp_expression', models.CharField(max_length=60)),
                ('emp_detelis', models.TextField()),
            ],
        ),
    ]
