# Generated by Django 5.0.1 on 2024-02-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empaccountdata',
            old_name='enp_name',
            new_name='emp_name',
        ),
    ]
