# Generated by Django 5.0.1 on 2024-02-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_enp_name_empaccountdata_emp_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empaccountdata',
            name='emp_category',
        ),
        migrations.RemoveField(
            model_name='empaccountdata',
            name='emp_field',
        ),
    ]
