# Generated by Django 5.0.1 on 2024-02-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_empaccountdata_emp_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_com_name', models.CharField(max_length=50)),
                ('in_com_mobile', models.CharField(max_length=50)),
                ('in_com_mail', models.CharField(max_length=50)),
                ('in_com_password', models.CharField(max_length=50)),
                ('in_com_address', models.TextField()),
                ('in_com_states', models.CharField(max_length=50)),
                ('in_com_logo', models.ImageField(upload_to='company_Logo')),
                ('in_com_informetion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='EmpAccountData',
        ),
    ]
