# Generated by Django 5.0.1 on 2024-02-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_companyaccount_delete_empaccountdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='in_com_mail',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='companyaccount',
            name='in_com_mobile',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='companyaccount',
            name='in_com_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='companyaccount',
            name='in_com_password',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='companyaccount',
            name='in_com_states',
            field=models.CharField(max_length=120),
        ),
    ]
