# Generated by Django 5.0.1 on 2024-02-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_companyaccount_in_com_mail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyaccount',
            old_name='in_com_address',
            new_name='dt_com_address',
        ),
        migrations.RenameField(
            model_name='companyaccount',
            old_name='in_com_informetion',
            new_name='dt_com_informetion',
        ),
        migrations.RenameField(
            model_name='companyaccount',
            old_name='in_com_logo',
            new_name='dt_com_logo',
        ),
        migrations.RenameField(
            model_name='companyaccount',
            old_name='in_com_mail',
            new_name='dt_com_mail',
        ),
        migrations.RenameField(
            model_name='companyaccount',
            old_name='in_com_mobile',
            new_name='dt_com_mobile',
        ),
        migrations.RenameField(
            model_name='companyaccount',
            old_name='in_com_name',
            new_name='dt_com_name',
        ),
        migrations.RenameField(
            model_name='companyaccount',
            old_name='in_com_password',
            new_name='dt_com_password',
        ),
        migrations.RenameField(
            model_name='companyaccount',
            old_name='in_com_states',
            new_name='dt_com_states',
        ),
    ]
