# Generated by Django 5.0.1 on 2024-02-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_rename_in_com_address_companyaccount_dt_com_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaccount',
            name='dt_com_logo',
        ),
    ]
