# Generated by Django 5.0.1 on 2024-02-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_remove_companyaccount_dt_com_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='companyAccount',
        ),
    ]
