# Generated by Django 5.0.1 on 2024-02-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0008_delete_companyaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_com_name', models.CharField(max_length=120)),
                ('dt_com_mobile', models.CharField(max_length=120)),
                ('dt_com_mail', models.CharField(max_length=120)),
                ('dt_com_password', models.CharField(max_length=120)),
                ('dt_com_address', models.TextField()),
                ('dt_com_states', models.CharField(max_length=120)),
                ('dt_com_logo', models.ImageField(upload_to='company_Logo')),
                ('dt_com_informetion', models.TextField()),
            ],
        ),
    ]
