# Generated by Django 5.0.1 on 2024-02-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='dt_com_logo',
            field=models.ImageField(upload_to='static/cmimg'),
        ),
    ]
