# Generated by Django 5.0.1 on 2024-02-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_alter_companyaccount_dt_com_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='dt_com_logo',
            field=models.ImageField(upload_to='comimg'),
        ),
    ]
