# Generated by Django 5.0.1 on 2024-02-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_companyaccount_dt_com_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_com_name', models.CharField(max_length=120)),
                ('c_job_title', models.CharField(max_length=120)),
                ('c_joblpg', models.CharField(max_length=120)),
                ('c_job_state', models.CharField(max_length=120)),
                ('c_job_pincode', models.CharField(max_length=120)),
                ('c_job_deteils', models.CharField(max_length=220)),
                ('c_job_recruitment', models.CharField(max_length=220)),
            ],
        ),
    ]
