# Generated by Django 5.0.2 on 2024-02-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_createpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_emp_name', models.CharField(max_length=120)),
                ('dt_emp_mobile', models.CharField(max_length=120)),
                ('dt_emp_mail', models.CharField(max_length=120)),
                ('dt_emp_password', models.CharField(max_length=120)),
                ('dt_emp_address', models.CharField(max_length=120)),
                ('dt_emp_states', models.CharField(max_length=120)),
                ('dt_emp_college_name', models.CharField(max_length=120)),
                ('dt_emp_marks', models.CharField(max_length=120)),
                ('dt_emp_education', models.CharField(max_length=120)),
                ('dt_emp_field', models.CharField(max_length=120)),
                ('dt_emp_Category', models.CharField(max_length=120)),
                ('dt_emp_Expression', models.CharField(max_length=120)),
                ('dt_emp_Resume', models.ImageField(max_length=300, upload_to='Employee_Resume/')),
                ('dt_emp_Dp', models.ImageField(max_length=300, upload_to='Employee_DP/')),
                ('dt_emp_detelis', models.TextField(max_length=800)),
            ],
        ),
    ]
