# Generated by Django 5.0.2 on 2024-02-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_employeeaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccount',
            name='dt_emp_Resume',
            field=models.FileField(max_length=300, upload_to='Employee_Resume/'),
        ),
    ]
