# Generated by Django 5.0.2 on 2024-02-19 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_alter_employeeaccount_dt_emp_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeaccount',
            name='dt_emp_Category',
        ),
        migrations.RemoveField(
            model_name='employeeaccount',
            name='dt_emp_Expression',
        ),
    ]
