# Generated by Django 5.0.2 on 2024-02-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_remove_employeeaccount_dt_emp_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatePost',
        ),
    ]
