# Generated by Django 5.0.2 on 2024-02-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_createpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='c_Post_id',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
