# Generated by Django 5.0.2 on 2024-02-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_createpost_c_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpJobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jp_emp_mobile', models.CharField(max_length=120)),
                ('jp_emp_name', models.CharField(max_length=120)),
                ('jp_emp_Dp', models.CharField(max_length=120)),
                ('jp_emp_detelis', models.CharField(max_length=120)),
                ('jp_emp_status', models.CharField(max_length=120)),
            ],
        ),
    ]
