# Generated by Django 5.0.2 on 2024-02-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_empjobpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpJobPost',
        ),
    ]
