# Generated by Django 5.0.2 on 2024-02-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_delete_empjobpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpJobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jp_Post_id', models.CharField(max_length=120)),
                ('jp_Com_id', models.CharField(max_length=120)),
                ('jp_emp_Dp', models.CharField(max_length=120)),
                ('jp_emp_id', models.CharField(max_length=120)),
                ('jp_emp_name', models.CharField(max_length=120)),
                ('jp_emp_info', models.CharField(max_length=120)),
                ('jp_emp_status', models.CharField(max_length=120)),
            ],
        ),
    ]
