# Generated by Django 5.0.2 on 2024-02-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_delete_empjobpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpJobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jp_Post_id', models.CharField(max_length=120)),
                ('jp_Com_id', models.CharField(max_length=120)),
                ('jp_emp_id', models.CharField(max_length=120)),
                ('jp_emp_Dp', models.CharField(max_length=120)),
                ('jp_emp_name', models.CharField(max_length=120)),
                ('jp_emp_info', models.CharField(max_length=120)),
                ('jp_emp_status', models.CharField(max_length=120)),
                ('jp_com_name', models.CharField(max_length=120)),
                ('jp_job_title', models.CharField(max_length=120)),
                ('jp_job_com_logo', models.CharField(max_length=120)),
                ('jp_joblpg', models.CharField(max_length=120)),
                ('jp_job_state', models.CharField(max_length=120)),
                ('jp_job_pincode', models.CharField(max_length=120)),
                ('jp_job_deteils', models.CharField(max_length=220)),
                ('jp_job_recruitment', models.CharField(max_length=220)),
            ],
        ),
    ]
